AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: laptopkey
      ImageId: ami-0cff7528ff583bf9a
      SecurityGroups:
        - default