AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the KeyName

Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-0cff7528ff583bf9a
      
    us-west-1:
      HVM64: ami-0d9858aa3c6322f73
  



Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      

