AWSTemplateFormatVersion: "2010-09-09"
Description: Outputs practice

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the KeyName
  MyEnvironmentName:
    Description: Select the Environment Name
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: must be dev or prod
Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-0cff7528ff583bf9a
    us-west-1:
      HVM64: ami-0d9858aa3c6322f73
  
  MyEnvironmentMap:
    dev:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small

    

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironmentName
        - InstanceType
      KeyName: !Ref MyKeyName
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      SecurityGroups:
       - !Ref MyDevGlobalSecurityGroup


  MyDevGlobalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    
    Properties:
      GroupDescription: My Dev Globla Environment
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Outputs:
  MyInstanceId:
    Description: My instance id
    Value: !Ref MyVMInstance
  MyDNSName:
    Description: MY public IP
    Value: !GetAtt MyVMInstance.PublicDnsName
  MyInstanceAvailabilityZone:
    Description: My instance AZ
    Value: !GetAtt MyVMInstance.AvailabilityZone
    Export:
      Name: !Sub "${AWS::StackName}-InstanceAz"
  
  MyDevGlobalSecurityGroup:
    Description: My Dev SG
    Value: !Ref MyDevGlobalSecurityGroup
    Export:
      Name: MyDevSSHGloal1
